### ISSUE TITLE
Most current job status not reflected everywhere when results folder setting is empty

### ISSUE THREAD

**Issue by marisademeglio** [daisy/pipeline-ui#212]
Feedback received from @rachanasinghg 
"
Currently I find the status of pipeline jobs a bit confusing, there is somewhat a difference in the Job title tab and result window.
I have attached a few screenshots for your reference.

For example in screenshot DP_Job1 , the result window pane shows Validation completed but the Job tab and status window shows status "Running".
Same goes for DP_Job2, DP_Job3 and DP_Job4 screenshot. The last text/sentence of the result pane does not indicate that Job is completed, or the job title tab should show  "Completed" instead of "Running". 
We need to check the result folder whether the file is complete or not. For files which have Error , the title also shows the exact thing so it's good but the other files do not show the same.
"
![DP_Job1](https://github.com/daisy/pipeline-ui/assets/734730/65f6cb11-94dc-4e51-a68d-b5fba8d89c78)
![DP_Job2](https://github.com/daisy/pipeline-ui/assets/734730/230c41b3-94ce-4432-a0a4-3ede013fcc7c)
![DP_Job3](https://github.com/daisy/pipeline-ui/assets/734730/3e49f4bc-55c8-4f69-9fca-0fd00638327a)
![DP_Job4](https://github.com/daisy/pipeline-ui/assets/734730/ecdb5309-62d9-452e-828d-2b76e155a8d5)

**Comment by marisademeglio** [comment]
> > @rachanasinghg does the status in the tab ever get updated to "Completed"?
> 
> Not till now.

So it never changes to "Completed"? 

Has this always been the case for you or is it new behavior?

**Comment by rachanasinghg** [comment]
Earlier I used to see the "Completed" status but not after the recent
update. Even after running the Job for 12 hours or more it still says
"Running".
This behaviour was not there in the previous release.
Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
Ok thanks for the clarification! Can you confirm the version that you're using and the version that you were using when it was working?

**Comment by rachanasinghg** [comment]
Hi Marisa,
Currently I am using the following version.

         App version: 1.2.7-RC1,
        Engine version: 1.14.16,
        Engine is running  on 127.0.0.1:49152/ws

Sorry, I am unable to find the previous installer which used to work for
me. Let me check again with different installers.
Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
Did you have any luck with older installers? Also if these results were with 1.2.7-RC1, maybe we could check with [1.2.7](https://github.com/daisy/pipeline-ui/releases/tag/1.2.7). Can you let me know if that behaves the same?

**Comment by rachanasinghg** [comment]
Hi Marisa,

I tried both the installers 1.2.7 -RC3 and 1.2.7, but none of them shows
jobs as "Completed", either its "Running" or "Error".

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
Ok thanks for testing the other versions, we will look into it. @NPavie do you notice this issue on Windows?

**Comment by marisademeglio** [comment]
I was not able to reproduce this with the upcoming 1.3.0 release after briefly testing it on Windows 11.

**Comment by marisademeglio** [comment]
@rachanasinghg Can you check with the [new release](https://github.com/daisy/pipeline-ui/releases/tag/1.3.0)? And if it's still an issue, could you email your log file found at %APPDATA%\pipeline-ui\logs\main.log ?

**Comment by rachanasinghg** [comment]
Hi Marisa,
 I checked the new release pipeline installer and sad to say it is still an
issue.
I am attaching the log file for your reference.
Thank you.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by NPavie** [comment]
Hi @rachanasinghg, sorry about that, we will continue to investigate.

Github did not forwarded the log file along your email for the team to look it up.
Can you send it to the team via a separate email to the [daisy-pipeline@mail.daisy.org](mailto:daisy-pipeline@mail.daisy.org) mailing list ?

I notice on the screenshot provided that it was all related to DAISY 2.02 input files, does it also act similarly on other scripts with different input format (like dtbook-based script) ?
Along the log file, could it be possible for you to provide us as a zip file of one of the Daisy2.02 book that is exposing this behaviour ?

**Comment by rachanasinghg** [comment]
Hello @NPavie ,

I have already sent the mail to [daisy-pipeline@mail.daisy.org](mailto:daisy-pipeline@mail.daisy.org)  , with 1 Zip file and 2 log files. Zip file has "Alice in wonderland" book which is one of the books throwing errors in conversion. There are 2 log files, file named as old_main contain the Daisy 2 conversion errors, which i had sent through mail. The other file named as  main_new contains the DAISY 3 conversion errors.

If you are still facing an issue in reading the file, please do let me know.
Thank you.

**Comment by NPavie** [comment]
@rachanasinghg sorry to bother you again, it seems the mail with the attachment did not passed trought the mailing list

Can you try to send it to me to pavie.nicolas@gmail.com ?

**Comment by rachanasinghg** [comment]
@Nicolas Pavie ***@***.***> I am sorry for the
inconvenience caused by the failure of my previous email to reach you.

I have sent 2 separate emails to you, one with the zip file and another
with log files.
Please check if it reaches you with the attached files, Thanks.

With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by marisademeglio** [comment]
@rachanasinghg can you try something? Run a job, wait a bit until when you would expect it to say "completed", and while it still says "running" instead, open this page in a browser:

http://localhost:49152/ws/jobs

and paste the output here. It should be an XML document. It might list nothing or it might list one or more jobs. It can tell us what the pipeline engine is reporting directly, and that might be informative.

**Comment by NPavie** [comment]
@rachanasinghg from the log I might have an idea of what is going on but just to confirm, can you do the following actions in the application ?
- Can you open the application settings, and give us back the value of the "Results folder" setting in the general section ?
- Can you select a different result folder using the browse button, close the settings, and then create and launch a new job ?

**Comment by rachanasinghg** [comment]
Hello Nicolas,

Thank you so much it worked, finally I can see the Complete status.

Regarding your queries , here are my answers under<RS>.


   - Can you open the application settings, and give us back the value of
   the "Results folder" setting in the general section ?<RS> Results folder
   text box was empty, so no value.


   - Can you select a different result folder using the browse button,
   close the settings, and then create and launch a new job ?<RS>  Through
   the Browse button I selected a folder path and ran a script. Ultimately the
   running status was changed to Completed /Error. I am attaching the
   screenshot.



With Regards
Rachana Singh
Usability & Testing Engineer | DAISY Consortium
<https://daisy.org/activities/software/obi/>

**Comment by NPavie** [comment]
Ok i was able to reproduce the issue i think (it came from the empty value in the Results folder field)

I'll update the issue name

**Comment by marisademeglio** [comment]
I am having issues with this, if I go under settings and clear the Results folder field, and run a job, it gets stuck mid-process. 

What's actually happening is that as soon as the job status is SUCCESS and it attempts to download the results, it says 

`Error downloading job results TypeError [ERR_INVALID_URL]: Invalid URL`

this doesn't happen when the Results folder is set.

```
12:54:58.761 › fetching  http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d null
[1] 12:54:58.777 › received job data  {
[1]   jobId: 'b741949c-aaf8-465f-bbd8-8774d651541d',
[1]   status: 'RUNNING',
[1]   href: 'http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d',
[1]   nicename: 'DTBook to braille',
[1]   messages: [ 'removed to keep log cleaner' ],
[1]   progress: 0,
[1]   script: {
[1]     id: 'dtbook-to-pef',
[1]     href: 'http://127.0.0.1:49152/ws/scripts/dtbook-to-pef',
[1]     nicename: 'DTBook to braille',
[1]     description: 'Transforms a DTBook (DAISY 3 XML) document into an embosser ready braille document.',
[1]     version: '10.0.1',
[1]     homepage: '',
[1]     inputs: [],
[1]     options: []
[1]   }
[1] }
[1] 12:54:59.765 › fetching  http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d null
[1] 12:54:59.797 › received job data  {
[1]   jobId: 'b741949c-aaf8-465f-bbd8-8774d651541d',
[1]   status: 'SUCCESS',
[1]   href: 'http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d',
[1]   nicename: 'DTBook to braille',
[1]   log: 'http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d/log',
[1]   results: {
[1]     href: 'http://127.0.0.1:49152/ws/jobs/b741949c-aaf8-465f-bbd8-8774d651541d/result',
[1]     mimeType: 'application/zip',
[1]     namedResults: [ [Object] ]
[1]   },
[1]   messages: [ 'removed to keep log cleaner' ],
[1]   progress: 1,
[1]   script: {
[1]     id: 'dtbook-to-pef',
[1]     href: 'http://127.0.0.1:49152/ws/scripts/dtbook-to-pef',
[1]     nicename: 'DTBook to braille',
[1]     description: 'Transforms a DTBook (DAISY 3 XML) document into an embosser ready braille document.',
[1]     version: '10.0.1',
[1]     homepage: '',
[1]     inputs: [],
[1]     options: []
[1]   }
[1] }
[1] 12:54:59.798 › Error downloading job results TypeError [ERR_INVALID_URL]: Invalid URL
[1]     at new NodeError (node:internal/errors:372:5)
[1]     at URL.onParseError (node:internal/url:553:9)
[1]     at new URL (node:internal/url:629:5)
[1]     at /Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:60147:51
[1]     at Array.map (<anonymous>)
[1]     at /Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:60146:164
[1]     at step (/Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:60030:23)
[1]     at Object.next (/Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:59971:20)
[1]     at asyncGeneratorStep (/Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:59849:28)
[1]     at _next (/Users/marisa/dev/pipeline-ui/node_modules/.dev-temp-build/main.js:59867:17)

```

**Comment by marisademeglio** [comment]
I don't know internally what would have to change in order to run jobs with no results folder specified, but it doesn't seem like desirable behavior so I disabled the ability to run jobs if there is not a results folder set in settings.
